name: Build and Test Notifier

on: 
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3.1.0
      with:
        python-version: "3.9"

    - name: Set up Poetry
      run: curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - -y
      shell: bash

    - name: Install dependencies
      run: make install
      shell: bash

    - name: Run tests
      run: make test
      shell: bash